from __future__ import annotations

import random
from typing import Dict, List, Optional

import z3

# Build z3 evaluation namespace once at import time to avoid repeated dict construction.
# eval() uses this to resolve Z3 constructors (Int, Bool, Real, And, Or, …) in
# constraint strings generated by the LLM reasoning pipeline.
_Z3_NS: Dict[str, object] = {
    k: getattr(z3, k) for k in dir(z3) if not k.startswith("__")
}


class SolverError(Exception):
    """Raised when Z3SolverWrapper encounters a parse failure or an illegal state
    transition (e.g. calling get_model() when the last result was UNSAT).
    """


class Z3SolverWrapper:
    """Thin, stateful wrapper around z3.Solver with string-based constraint management.

    All constraints are added via assert_and_track so that unsat-core extraction is
    always available without a separate solver configuration step. The wrapper stores
    the original constraint strings alongside Z3 tracking variables, enabling
    round-trip conversion between human-readable strings and Z3 expressions.

    Typical usage::

        solver = Z3SolverWrapper()
        solver.add_constraint("Int('x') > 0")
        solver.add_constraint("Int('x') < 0")
        result = solver.check()          # "UNSAT"
        core   = solver.get_unsat_core() # ["Int('x') > 0", "Int('x') < 0"]
    """

    def __init__(self) -> None:
        """Initialise an empty Z3 solver with constraint tracking structures."""
        self._solver: z3.Solver = z3.Solver()
        self._constraint_strs: List[str] = []
        self._track_to_str: Dict[str, str] = {}
        self._track_counter: int = 0

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _parse(self, constraint_str: str) -> z3.BoolRef:
        """Evaluate *constraint_str* in the z3 namespace and return the expression.

        Raises SolverError if the string cannot be parsed or does not produce a
        Boolean Z3 expression.
        """
        try:
            expr = eval(constraint_str, _Z3_NS)  # noqa: S307
        except Exception as exc:
            raise SolverError(
                f"Cannot parse constraint: {constraint_str!r}"
            ) from exc
        if not z3.is_bool(expr):
            raise SolverError(
                f"Constraint must evaluate to a Z3 Boolean, got {type(expr).__name__!r}"
                f" for: {constraint_str!r}"
            )
        return expr  # type: ignore[return-value]

    def _fresh_track_name(self) -> str:
        """Return a unique internal tracking variable name."""
        name = f"_prism_track_{self._track_counter}"
        self._track_counter += 1
        return name

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def add_constraint(self, constraint_str: str) -> bool:
        """Parse *constraint_str* and add it to the solver via assert_and_track.

        Using assert_and_track (rather than plain assert) registers a Boolean
        tracking literal alongside each constraint, which Z3 needs to produce an
        unsat core on demand.

        Args:
            constraint_str: A Z3 Python-API expression as a string, e.g.
                ``"And(Int('x') > 0, Int('y') < 10)"``.

        Returns:
            True if the constraint was syntactically valid and added successfully,
            False if parsing failed (the solver state is unchanged).
        """
        try:
            expr = self._parse(constraint_str)
        except SolverError:
            return False

        track_name = self._fresh_track_name()
        track_var = z3.Bool(track_name)
        self._solver.assert_and_track(expr, track_var)
        self._constraint_strs.append(constraint_str)
        self._track_to_str[track_name] = constraint_str
        return True

    def check(self) -> str:
        """Run the solver and return the satisfiability verdict.

        Returns:
            ``"SAT"`` if the constraint set is satisfiable, ``"UNSAT"`` if it is
            provably unsatisfiable, or ``"UNKNOWN"`` if the solver timed out or
            gave up.
        """
        result = self._solver.check()
        if result == z3.sat:
            return "SAT"
        if result == z3.unsat:
            return "UNSAT"
        return "UNKNOWN"

    def get_unsat_core(self) -> List[str]:
        """Return the minimal unsatisfiable constraint subset as original strings.

        Internally calls check() to confirm UNSAT status, then reads Z3's unsat
        core and maps tracking literals back to the original string representations.

        Returns:
            List of constraint strings that form a minimal unsatisfiable subset.

        Raises:
            SolverError: If the current constraint set is not UNSAT.
        """
        if self._solver.check() != z3.unsat:
            raise SolverError(
                "get_unsat_core() is only valid after the solver returns UNSAT."
            )
        core_vars = self._solver.unsat_core()
        return [
            self._track_to_str[str(var)]
            for var in core_vars
            if str(var) in self._track_to_str
        ]

    def get_model(self) -> Dict[str, str]:
        """Return variable assignments as ``{name: value}`` strings when SAT.

        Z3 model values are converted to strings for portability; callers that
        need Z3 expression objects should access ``self._solver.model()`` directly.

        Returns:
            Dict mapping each declared variable name to its assigned value.

        Raises:
            SolverError: If the current constraint set is not SAT.
        """
        if self._solver.check() != z3.sat:
            raise SolverError(
                "get_model() is only valid after the solver returns SAT."
            )
        model = self._solver.model()
        return {
            str(decl): str(model[decl])
            for decl in model
            if not str(decl).startswith("_prism_track_")
        }

    def add_negated_constraint(self, constraint_str: str) -> bool:
        """Parse *constraint_str* and assert its logical negation.

        Used by paradigm non-vacuousness checks: asserting ``pre ∧ ¬op`` and
        testing SAT determines whether the operation is implied by the
        pre-condition. If SAT, there exists a state where ``pre`` holds but
        ``op`` does not — i.e. ``op`` is genuinely informative.

        Args:
            constraint_str: A Z3 Python-API expression as a string, evaluating
                to a Boolean expression that will be negated before assertion.

        Returns:
            True on success, False if parsing failed (solver unchanged).
        """
        try:
            expr = self._parse(constraint_str)
        except SolverError:
            return False

        track_name = self._fresh_track_name()
        track_var = z3.Bool(track_name)
        self._solver.assert_and_track(z3.Not(expr), track_var)
        canonical = f"Not({constraint_str})"
        self._constraint_strs.append(canonical)
        self._track_to_str[track_name] = canonical
        return True

    def reset(self) -> None:
        """Clear all constraints and tracking state, returning the solver to its
        initial empty configuration.
        """
        self._solver.reset()
        self._constraint_strs.clear()
        self._track_to_str.clear()
        self._track_counter = 0

    def clone(self) -> Z3SolverWrapper:
        """Return a new Z3SolverWrapper with the same constraint set.

        Constraints are re-added via add_constraint so that tracking variables are
        fully reproduced in the clone. Use clones for speculative / trial repairs
        without mutating the canonical solver state.

        Returns:
            A new Z3SolverWrapper instance whose constraint set is identical to
            the current one at the moment of cloning.
        """
        twin = Z3SolverWrapper()
        for c in self._constraint_strs:
            twin.add_constraint(c)
        return twin

    def get_constraints(self) -> List[str]:
        """Return the list of constraint strings added to this solver.

        Returns:
            List of constraint strings (in the order they were added).
        """
        return list(self._constraint_strs)

    def get_variables(self) -> List[str]:
        """Return variable names mentioned in current constraints.

        Extracts all Int(...) variable names from constraint strings using regex.

        Returns:
            Sorted list of unique variable names, e.g. ['color_Blue', 'color_Green', ...].
        """
        import re
        names: set = set()
        for c in self._constraint_strs:
            names.update(re.findall(r"Int\('([^']+)'\)", c))
        return sorted(names)

    def verify_paradigm_soundness(
        self,
        current_constraints: List[str],
        paradigm_assertion: str,
        n_trials: int = 20,
    ) -> float:
        """Estimate the soundness of a paradigm repair over random constraint subsets.

        For each trial a random non-empty subset of *current_constraints* is drawn,
        *paradigm_assertion* is appended, and a fresh solver is run. The soundness
        score is the fraction of trials that yield SAT, measuring how broadly
        compatible the proposed repair is with partial views of the constraint set.

        A score near 1.0 indicates the paradigm is almost always safe to apply;
        a score near 0.0 suggests it introduces frequent contradictions and should
        not be used.

        Args:
            current_constraints: Full pool of constraints to sample subsets from.
            paradigm_assertion: The repair assertion proposed by the paradigm.
            n_trials: Number of independent random trials (default 20).

        Returns:
            Float in [0.0, 1.0]. Returns 0.0 if *current_constraints* is empty or
            *n_trials* is non-positive.
        """
        if not current_constraints or n_trials <= 0:
            return 0.0

        passed = 0
        for _ in range(n_trials):
            k = random.randint(1, len(current_constraints))
            subset = random.sample(current_constraints, k)

            trial = Z3SolverWrapper()
            for c in subset:
                trial.add_constraint(c)
            trial.add_constraint(paradigm_assertion)

            if trial.check() == "SAT":
                passed += 1

        return passed / n_trials
