$pdf_mode = 5;
$xelatex = 'xelatex -interaction=nonstopmode -file-line-error -synctex=1 %O %S';
$bibtex = 'bibtex %O %B';
$clean_ext = 'aux bbl blg fdb_latexmk fls log out synctex.gz toc xdv';
$clean_full_ext = 'bbl';
