"""Layer-1 constraint-type matching for paradigm retrieval.

``ParadigmRetriever`` provides a fast, LLM-free first-pass filter over the
paradigm library.  The retriever ranks candidates by a weighted combination of
scope-Jaccard similarity and paradigm confidence, then returns the top-k results
to the caller.  Semantic (Layer-2) filtering is intentionally left to the caller
(``GuidedSolver``) so that the retriever stays stateless and testable without
an LLM dependency.
"""

from __future__ import annotations

from typing import List, Optional

from prism.paradigm_library.schema import Paradigm

_W_SCOPE_JACCARD: float = 0.60
_W_CONFIDENCE: float = 0.40

_MIN_JACCARD_THRESHOLD: float = 0.01


def _jaccard(a: set, b: set) -> float:
    union = a | b
    return len(a & b) / len(union) if union else 0.0


# --- Relational predicate evaluation -----------------------------------------
#
# A paradigm's ``trigger`` dict may optionally contain a ``relational_predicates``
# list. Each entry is a dict ``{"kind": "<name>", ...args}`` evaluated against
# the current constraint-type bag (a list with repetitions). Supported kinds:
#
#   - ``count_atleast``: ``{"kind": "count_atleast", "type": "<t>", "n": <int>}``
#       Fires if at least ``n`` occurrences of constraint type ``t`` are
#       currently present.
#   - ``count_atmost``:  ``{"kind": "count_atmost",  "type": "<t>", "n": <int>}``
#       Fires if at most ``n`` occurrences are present (useful for paradigms
#       that apply only when a type is rare or absent).
#   - ``cooccur``:       ``{"kind": "cooccur", "types": ["<t1>", "<t2>"]}``
#       Fires if all listed types are present at least once.
#
# Unknown predicate kinds are treated as a soft-pass (do not filter the
# paradigm out) so that paradigms generated by future iterations of the
# distillation pipeline remain backward-compatible.

def _eval_predicate(pred: dict, type_bag: List[str]) -> bool:
    kind = (pred.get("kind") or "").strip().lower()
    if not kind:
        return True
    if kind == "count_atleast":
        t = pred.get("type", "")
        n = int(pred.get("n", 1))
        return type_bag.count(t) >= n
    if kind == "count_atmost":
        t = pred.get("type", "")
        n = int(pred.get("n", 0))
        return type_bag.count(t) <= n
    if kind == "cooccur":
        ts = pred.get("types", []) or []
        return all(t in type_bag for t in ts)
    return True  # unknown kind → soft-pass


def _predicates_satisfied(trigger: dict, type_bag: List[str]) -> bool:
    preds = (trigger or {}).get("relational_predicates")
    if not preds:
        return True  # no predicates declared → set-membership match alone suffices
    return all(_eval_predicate(p, type_bag) for p in preds)


class ParadigmRetriever:
    """Stateless Layer-1 paradigm retriever based on constraint-type set matching.

    Ranking formula::

        score(p) = 0.60 × Jaccard(p.scope, query_types) + 0.40 × p.confidence

    The retriever also evaluates any ``relational_predicates`` declared on a
    paradigm's ``trigger`` dict (count_atleast / count_atmost / cooccur) against
    the actual constraint-type bag. Paradigms whose predicates do not hold are
    pruned *before* ranking — this lifts Layer-1 from pure type-set membership
    to a richer set-with-multiplicity match while remaining LLM-free and O(N).

    When no paradigm has any scope overlap with the query (all Jaccard scores
    are zero), the retriever falls back to ranking by confidence alone so that
    the caller always receives *k* candidates to pass to Layer-2 filtering.

    This class has no external dependencies beyond ``schema.Paradigm`` and is
    therefore suitable for use in unit tests without a running LLM or solver.
    """

    def retrieve(
        self,
        paradigms: List[Paradigm],
        constraint_types: List[str],
        top_k: int = 3,
        type_bag: Optional[List[str]] = None,
        min_confidence: float = 0.0,
    ) -> List[Paradigm]:
        """Return the top-k paradigms ranked by scope relevance and confidence.

        Args:
            paradigms: Full list of paradigms to rank.
            constraint_types: Distinct tags describing the types of constraints
                currently present (de-duplicated set form).
            top_k: Maximum number of results to return.
            type_bag: Optional repetition-preserving list of constraint types
                used to evaluate relational predicates. When omitted, defaults
                to ``constraint_types`` itself (no multiplicity information).

        Returns:
            List of up to *top_k* :class:`~prism.paradigm_library.schema.Paradigm`
            objects sorted by relevance descending.
        """
        if not paradigms:
            return []

        # Confidence floor (paper §Layer-1: τ_conf) applies before ranking,
        # including the zero-overlap confidence fallback below.
        paradigms = [p for p in paradigms if p.confidence >= min_confidence]
        if not paradigms:
            return []

        bag = type_bag if type_bag is not None else list(constraint_types)
        eligible = [p for p in paradigms if _predicates_satisfied(p.trigger, bag)]
        if not eligible:
            return []

        query_set = set(constraint_types)
        scored = [
            (self._score(p, query_set), p)
            for p in eligible
        ]
        scored.sort(key=lambda t: t[0], reverse=True)

        if scored[0][0] < _MIN_JACCARD_THRESHOLD:
            by_conf = sorted(eligible, key=lambda p: p.confidence, reverse=True)
            return by_conf[:top_k]

        return [p for _, p in scored[:top_k]]

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _scope_jaccard(paradigm_scope: List[str], query_types: set) -> float:
        return _jaccard(set(paradigm_scope), query_types)

    def _score(self, paradigm: Paradigm, query_set: set) -> float:
        jaccard = self._scope_jaccard(paradigm.scope, query_set)
        return _W_SCOPE_JACCARD * jaccard + _W_CONFIDENCE * paradigm.confidence
